# Generated by Django 2.0.13 on 2019-06-13 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinball', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinballinstance',
            old_name='game',
            new_name='pinball',
        ),
        migrations.AlterField(
            model_name='pinball',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinball.Release_Year'),
        ),
    ]
