# Generated by Django 2.0.13 on 2019-06-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinball', '0002_auto_20190612_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinball',
            name='coils',
            field=models.ManyToManyField(blank=True, help_text='Select the coils used in this game', to='pinball.Coil'),
        ),
        migrations.AlterField(
            model_name='pinball',
            name='parts',
            field=models.ManyToManyField(blank=True, help_text='Add parts specific to this game', to='pinball.Parts'),
        ),
    ]
