# Generated by Django 2.0.13 on 2019-06-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinball', '0004_auto_20190615_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-name']},
        ),
    ]
