# Generated by Django 2.0.13 on 2019-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinball', '0012_remove_pinballinstance_repairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, help_text='Enter the address', null=True),
        ),
    ]
