# Generated by Django 2.0.13 on 2019-08-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinball', '0015_auto_20190619_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['pk']},
        ),
    ]
